### ISSUE TITLE
Tool crashes when run with example data

### ISSUE THREAD

**Issue by TillF** [yingkui2003/topo-shielding#1]
Thanks for making the tool available.
However, I am trying to run the tool with the example data provided in ArcMap 10.8.1 (Spatial Analyst, 3D-Analyst) on Windows.
The script starts running, then terminates with the following message:

```
Executing: pointShielding tsutm90.tif Newshieldingpoints # # # # U:\topo_shielding\test.shp
Start Time: Fri Jun  9 09:39:16 2023
Running script pointShielding...
The current python version is: 2
Processing Point #1 of 10
Failed script pointShielding...

Traceback (most recent call last):
  File "U:\topo_shielding\Pointshield\Point-based Topographic Shielding Python.tbx#pointShielding_pShielding.py", line 188, in <module>
  File "d:\arcgis\desktop10.8\arcpy\arcpy\management.py", line 3647, in CalculateField
    raise e
ExecuteError: ERROR 999999: Error executing function.
Anweisungsende erwartet
Failed to execute (CalculateField).


Failed to execute (pointShielding).
Failed at Fri Jun  9 09:39:18 2023 (Elapsed Time: 1,59 seconds)
```
"Anweisungsende erwartet" translates to "End of command expected".
I tested both the old and the new version of the script.
What am I doing wrong?

**Comment by Alosika** [comment]
Hello, unfortunately, I have the same error. Have you found what is wrong?

**Comment by TillF** [comment]
I tried different computers with different combinations of ArcGIS, Python and Windows version, and it succeeded on one of them.
However, I could not find out what the reason was. I will report if there are any news...

**Comment by Alosika** [comment]
Do you know similar tools for calculating topographic shielding from DEMs?

wt., 16 sty 2024, 11:18 użytkownik Till Francke ***@***.***>
napisał:

**Comment by TillF** [comment]
No, but please let me know if you find one.

**Comment by Alosika** [comment]
Hi, I asked two more people to try, and one was able to calculate it very smoothly, but I do not know why. We all used the same version of ArcGIS.
If you are looking for a very easy but a bit more time-consuming solution, I have found some. If you have a DEM and 3D points, you can use the toolbox "Skyline" and then "Skyline Graph" (and generate the table). From the table, you can take the values of the horizontal geographic angles and the elevation angles and paste or type them into the Topographic shielding calculator: https://stoneage.ice-d.org/math/skyline/skyline_in.html, and add the dip and strike. It will be less precise than using the toolbox, but what about studies using only field measurements?
"Skyline Graph" has more options in ArcGIS Pro. In ArcMap, you would need additional calculations as you only get the horizontal angles (arithmetic, not geographical) and zenith angles (not the elevation angles: https://pro.arcgis.com/en/pro-app/3.1/help/analysis/3d-analyst/generate-a-skyline-analysis.htm)

**Comment by TillF** [comment]
Thanks for sharing these insights. Hoewever, I am looking for a solution to compute the shiellding factors for an entire area, not only single points. Your workaround seems to help only for single points. Thanks nonetheless.
